// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3k2C-K3gLPdFCpE6auE4BKj8DcDW8ZaQ',
    appId: '1:440128963278:web:f949c1eef74e3f16b9069f',
    messagingSenderId: '440128963278',
    projectId: 'killerapp-3e5d2',
    authDomain: 'killerapp-3e5d2.firebaseapp.com',
    storageBucket: 'killerapp-3e5d2.appspot.com',
    measurementId: 'G-WCR9PRPE03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP2IKUhfSrUB2gLlrpG7a13prok7naNv8',
    appId: '1:440128963278:android:ae0021729d0db3edb9069f',
    messagingSenderId: '440128963278',
    projectId: 'killerapp-3e5d2',
    storageBucket: 'killerapp-3e5d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwTUwhcApONvi2XX8JgECyFccp5Lo6D0',
    appId: '1:440128963278:ios:3f12dc26d440863fb9069f',
    messagingSenderId: '440128963278',
    projectId: 'killerapp-3e5d2',
    storageBucket: 'killerapp-3e5d2.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwTUwhcApONvi2XX8JgECyFccp5Lo6D0',
    appId: '1:440128963278:ios:e5606be98ba34fa5b9069f',
    messagingSenderId: '440128963278',
    projectId: 'killerapp-3e5d2',
    storageBucket: 'killerapp-3e5d2.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
